import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Homepage from '../components/Homepage'
export default function Home() {
  return (
    <>
      <Head>
        <title>GoalFi@lokesh_danu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Homepage></Homepage>
    </>
  )
}
